backend/backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import routers, permissions

from account.api.views import BankAccountViewSet
from account.views import HomePage
from card.api.views import CardViewSet
from transfer.api.views import TransferViewSet


schema_view = get_schema_view(
   openapi.Info(
      title="Bank API",
      default_version='v1',
      description="RESTful API for Bank.",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.IsAuthenticatedOrReadOnly,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', HomePage.as_view(), name='index'),
    path('account/', include('account.urls', namespace='account')),
    path('transfer/', include('transfer.urls', namespace='transfer')),
    path('card/', include('card.urls', namespace='card'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


router = routers.DefaultRouter()
router.register('bank-accounts', BankAccountViewSet, 'bank-account')
router.register('transfers', TransferViewSet, 'transfer')
router.register('cards', CardViewSet, 'card')

urlpatterns_api = [
    path('api/', include(router.urls)),
    path('api/swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

urlpatterns += urlpatterns_api

handler404 = 'account.views.custom_page_not_found'
handler500 = 'account.views.custom_server_error'
handler403 = 'account.views.custom_permission_denied'
handler400 = 'account.views.custom_bad_request'

backend/card/urls.py
from django.urls import path

from card.views import *

app_name = 'card'

urlpatterns = [
    path('list/', CardListView.as_view(), name='list'),
    path('detail/<pk>', CardDetailView.as_view(), name='detail'),
    path('create/', CardCreateView.as_view(), name='create')
]

backend/card/models.py
from creditcards.models import CardNumberField, CardExpiryField, SecurityCodeField
from django.core.validators import MaxValueValidator
from django.db import models

from account.models import BankAccount


class Card(models.Model):
    account = models.OneToOneField(BankAccount, on_delete=models.CASCADE, related_name='card')
    is_active = models.BooleanField(default=False)
    number = CardNumberField('card number')
    expires_date = CardExpiryField('expiration date', default='01/25')
    code = SecurityCodeField('security code')
    pin = models.PositiveIntegerField(validators=[MaxValueValidator(9999)])
    daily_online_limit = models.PositiveIntegerField(blank=True, null=True, default=2000)
    daily_withdrawal_limit = models.PositiveIntegerField(default=2000)
    monthly_online_limit = models.PositiveIntegerField(default=5000)
    monthly_withdrawal_limit = models.PositiveIntegerField(default=5000)

    def __str__(self):
        return 'Card account: {}'.format(self.account)

backend/card/forms.py
from django import forms

from account.models import BankAccount
from card.models import Card


class CardCreateForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ['account',
                  'number',
                  'code',
                  'pin',
                  'daily_online_limit',
                  'daily_withdrawal_limit',
                  'monthly_online_limit',
                  'monthly_withdrawal_limit']

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if user:
            self.fields['account'].queryset = BankAccount.objects.filter(user=user, card__isnull=True)

        for field_name in self.fields:
            field = self.fields.get(field_name)
            if field:
                field.widget.attrs.update({
                    'class': 'form-control',
                    'placeholder': field.label
                })

backend/card/api/views.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import OrderingFilter
# from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.viewsets import ModelViewSet

from card.api.filters import CardFilter
from card.api.serializers import CardSerializer
from card.models import Card


class CardViewSet(ModelViewSet):
    queryset = Card.objects.all()
    serializer_class = CardSerializer
    # permission_classes = (IsAuthenticatedOrReadOnly,)
    filter_backends = (DjangoFilterBackend, OrderingFilter,)
    filterset_class = CardFilter

    # def get_queryset(self):
    #     return Card.objects.filter(account__user=self.request.user)

backend/card/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView

from card.forms import CardCreateForm
from card.models import Card


class CardCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Card
    form_class = CardCreateForm
    template_name = 'card/create.html'
    success_url = reverse_lazy('index')
    success_message = "Your card was created successfully."

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class CardListView(LoginRequiredMixin, ListView):
    model = Card
    template_name = 'card/list.html'


class CardDetailView(LoginRequiredMixin, DetailView):
    model = Card
    template_name = 'card/detail.html'

backend/templates/card/create.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}{{ block.super }} - Card Create{% endblock title %}

{% block content %}

    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Create Card!</h1>
                    </div>
                    <form action="{{ app_path }}" method="post" class="user">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.account }}
                        </div>
                        <div class="form-group">
                            {{ form.number }}
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                {{ form.code }}
                            </div>
                            <div class="col-sm-6">
                                {{ form.pin }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                {{ form.daily_online_limit }}
                            </div>
                            <div class="col-sm-6">
                                {{ form.daily_withdrawal_limit }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                {{ form.monthly_online_limit }}
                            </div>
                            <div class="col-sm-6">
                                {{ form.monthly_withdrawal_limit }}
                            </div>
                        </div>
                        <hr>
                        <button type="submit" class="btn btn-primary btn-user btn-block">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content%}

backend/templates/card/detail.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}{{ block.super }} - Card Detail{% endblock title %}
{% block head_scripts_additional %}
    <link href="{% static 'css/details.scss' %}" rel="stylesheet" type="text/css">
{% endblock head_scripts_additional %}

{% block content %}

    <div class="container">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Card Bank</h1>
        </div>
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Info</h6>
            </div>
            <div class="card-body module">
                <h1><strong>Card number:</strong> {{ object.number }}</h1>
                <div class="card-details-row card-details-row-1-2">
                    <div>
                       <span>Card holder</span>
                       <p>{{ object.account }}</p>
                    </div>
                    <div>
                       <span>Expiration date</span>
                       <p>
                          {{ object.expires_date }}
                       </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content%}

backend/templates/card/list.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}{{ block.super }} - Card List{% endblock title %}


{% block content %}

    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Cards</h1>
        </div>
        <div class="card shadow mb-4">
            <div class="card-header py-3 justify-content-between d-flex">
                <h6 class="m-0 font-weight-bold text-primary">List</h6>
                <a href="{% url 'card:create' %}" class="btn btn-primary">
                    New Card
                </a>
            </div>
            <div class="card-body">
                <p>There are {{ object_list.count }} cards right now!</p>
                <div class="list-group">
                    {% for card in object_list %}
                          <a href="{% url 'card:detail' pk=card.pk %}" class="list-group-item list-group-item-action">
                             <div class="d-flex w-100 justify-content-between">
                                 <h5 class="mb-1">Credit Card</h5>
                                 <small class="text-muted">
                                   Expires: {{ card.expires_date }}
                                 </small>
                             </div>
                             <p class="mb-1">Number: {{ card.number }}</p>
                             <small class="text-muted">
                                Daily limits: {{ card.daily_online_limit }} (online), {{ card.daily_withdrawal_limit }} (withdrawal)
                             </small>
                             <br />
                             <small class="text-muted">
                                Monthly limits: {{ card.monthly_online_limit }} (online), {{ card.monthly_withdrawal_limit }} (withdrawal)
                             </small>
                          </a>
                        <br />
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock content%}