backend/backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import routers, permissions

from account.api.views import BankAccountViewSet
from account.views import HomePage
from card.api.views import CardViewSet
from transfer.api.views import TransferViewSet


schema_view = get_schema_view(
   openapi.Info(
      title="Bank API",
      default_version='v1',
      description="RESTful API for Bank.",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.IsAuthenticatedOrReadOnly,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', HomePage.as_view(), name='index'),
    path('account/', include('account.urls', namespace='account')),
    path('transfer/', include('transfer.urls', namespace='transfer')),
    path('card/', include('card.urls', namespace='card'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


router = routers.DefaultRouter()
router.register('bank-accounts', BankAccountViewSet, 'bank-account')
router.register('transfers', TransferViewSet, 'transfer')
router.register('cards', CardViewSet, 'card')

urlpatterns_api = [
    path('api/', include(router.urls)),
    path('api/swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

urlpatterns += urlpatterns_api

handler404 = 'account.views.custom_page_not_found'
handler500 = 'account.views.custom_server_error'
handler403 = 'account.views.custom_permission_denied'
handler400 = 'account.views.custom_bad_request'

backend/card/urls.py
from django.urls import path

from card.views import *

app_name = 'card'

urlpatterns = [
    path('list/', CardListView.as_view(), name='list'),
    path('detail/<pk>', CardDetailView.as_view(), name='detail'),
    path('create/', CardCreateView.as_view(), name='create')
]

backend/transfer/urls.py
from django.urls import path

from transfer.views import *

app_name = 'transfer'

urlpatterns = [
    path('list/incoming/', IncomingTransferListView.as_view(), name='list-incoming'),
    path('list/outgoing/', OutgoingTransferListView.as_view(), name='list-outgoing'),
    path('detail/<pk>', TransferDetailView.as_view(), name='detail'),
    path('create/', TransferCreateView.as_view(), name='create')
]

backend/transfer/models.py
from django.db import models

from account.models import BankAccount, User


class Transfer(models.Model):
    PLN = 'PLN'
    EUR = 'EUR'
    GBP = 'GBP'
    CURRENCY_TYPE = [
        (PLN, 'PLN'),
        (EUR, 'EUR'),
        (GBP, 'GBP')
    ]
    FAILED = 'FD'
    PANDING = "PG"
    COMPLETE = 'CT'
    STATUS_TYPE = [
        (FAILED, 'Failed'),
        (PANDING, 'Panding'),
        (COMPLETE, 'Complete')
    ]
    NORMAL = 'NL'
    EXPRESS = 'EX'
    METHOD_TYPE = [
        (NORMAL, 'Normal'),
        (EXPRESS, 'Express')
    ]
    sender = models.ForeignKey(BankAccount, on_delete=models.CASCADE, related_name='sender_transfers')
    receiver = models.ForeignKey(BankAccount, on_delete=models.CASCADE, related_name='receiver_transfers')
    title = models.CharField(max_length=140)
    amount = models.DecimalField(max_digits=9, decimal_places=2)
    currency = models.CharField(max_length=3, choices=CURRENCY_TYPE, default=PLN)
    reference = models.CharField(max_length=40)
    status = models.CharField(max_length=2, choices=STATUS_TYPE, default=PANDING)
    method = models.CharField(max_length=2, choices=METHOD_TYPE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Sender: {} | Receiver: {} | Amount: {}'.format(self.sender.user.email,
                                                               self.receiver.user.email,
                                                               self.amount)

backend/transfer/forms.py
from django import forms
from django.core.exceptions import ValidationError

from account.models import BankAccount, User
from transfer.models import Transfer


class TransferCreateForm(forms.ModelForm):

    class Meta:
        model = Transfer
        fields = ['sender', 'receiver', 'title', 'amount', 'reference', 'method']

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if user:
            self.fields['sender'].queryset = BankAccount.objects.filter(user=user, currency='PLN')
            self.fields['receiver'].queryset = BankAccount.objects.exclude(user=user, currency='PLN')

        for field_name in self.fields:
            field = self.fields.get(field_name)
            if field:
                field.widget.attrs.update({
                    'class': 'form-control',
                    'placeholder': field.label
                })

    def clean_amount(self):
        sender = self.cleaned_data.get('sender')
        amount = self.cleaned_data.get('amount')

        if sender and amount and amount > sender.current_balance:
            raise ValidationError("Amount too much!")
        return amount

backend/transfer/api/views.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import OrderingFilter
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.viewsets import ModelViewSet

from transfer.api.filters import TransferFilter
from transfer.api.serializers import TransferSerializer
from transfer.models import Transfer


class TransferViewSet(ModelViewSet):
    queryset = Transfer.objects.all()
    serializer_class = TransferSerializer
    # permission_classes = (IsAuthenticatedOrReadOnly,)
    filter_backends = (DjangoFilterBackend, OrderingFilter,)
    filterset_class = TransferFilter

    # def get_queryset(self):
    #     return Transfer.objects.filter(sender__user=self.request.user, receiver__user=self.request.user)

backend/transfer/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView

from account.models import BankAccount
from transfer.forms import TransferCreateForm
from transfer.models import Transfer


class TransferCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Transfer
    form_class = TransferCreateForm
    template_name = 'transfer/create.html'
    success_url = reverse_lazy('index')
    success_message = "Your transfer was created successfully."

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get(self, request, *args, **kwargs):
        if request.is_ajax and request.GET.get('sender'):
            sender = BankAccount.objects.get(pk=request.GET.get('sender'))
            return JsonResponse({'sender_max_amount': sender.current_balance})
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.status = 'CT'
        sender = form.cleaned_data.get('sender')
        receiver = form.cleaned_data.get('receiver')
        amount = form.cleaned_data.get('amount')

        # Update current balance sender and receiver
        sender.current_balance -= amount
        receiver.current_balance += amount
        sender.save()
        receiver.save()
        return super().form_valid(form)


class IncomingTransferListView(LoginRequiredMixin, ListView):
    model = Transfer
    template_name = 'transfer/incoming_list.html'

    def get_queryset(self):
        return Transfer.objects.filter(receiver__in=self.request.user.bank_accounts.all())


class OutgoingTransferListView(LoginRequiredMixin, ListView):
    model = Transfer
    template_name = 'transfer/outgoing_list.html'

    def get_queryset(self):
        return Transfer.objects.filter(sender__in=self.request.user.bank_accounts.all())


class TransferDetailView(LoginRequiredMixin, DetailView):
    model = Transfer
    template_name = 'transfer/detail.html'

backend/templates/transfer/create.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}{{ block.super }} - Transfer Create{% endblock title %}

{% block content %}

    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Create Transfer!</h1>
                    </div>
                    <form action="{{ app_path }}" method="post" class="user">
                        {% csrf_token %}
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                {{ form.sender }}
                            </div>
                            <div class="col-sm-6">
                                {{ form.receiver }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                {{ form.title }}
                            </div>
                            <div class="col-sm-6">
                                {{ form.amount }}
                            </div>
                        </div>
                        <div class="form-group">
                            {{ form.reference }}
                        </div>
                        <div class="form-group">
                            {{ form.method }}
                        </div>
                        <hr>
                        <button type="submit" class="btn btn-primary btn-user btn-block">Send Money</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content%}

{% block body_scripts_additional %}
    <script>
        $("#id_sender").focusout(function (e) {
            e.preventDefault();
            // GET sender account id
            const sender = $(this).val();
            // GET AJAX request
            $.ajax({
                type: 'GET',
                url: "{% url 'transfer:create' %}",
                data: {
                    sender: sender,
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                },
                success: function (response) {
                    const senderMaxAmount = response['sender_max_amount'];
                    $("#id_amount").attr({
                        'max': senderMaxAmount
                    })
                },
                error: function (error) {
                    console.log(error)
                }
            })
        });
    </script>
{% endblock %}

backend/templates/transfer/detail.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}{{ block.super }} - Transfer Detail{% endblock title %}

{% block content %}

    <div class="container">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Transfer Bank</h1>
        </div>
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Info</h6>
            </div>
            <div class="card-body module">
                <h1><strong>Transfer:</strong>{{ object.get_method_display }}</h1>
                <ul>
                    <li>Date: {{ object.sender }}</li>
                    <li>Title: {{ object.receiver }}</li>
                    <li>Date: {{ object.created }}</li>
                    <li>Title: {{ object.title }}</li>
                    <li>Amount: {{ object.amount }}</li>
                    <li>Type: {{ object.get_method_display }}</li>
                    <li>Status: {{ object.get_status_display }}</li>
                </ul>
            </div>
        </div>
    </div>

{% endblock content%}

backend/templates/transfer/incoming_list.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}{{ block.super }} - Transfers List{% endblock title %}


{% block content %}

    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Transfers</h1>
        </div>
        <div class="card shadow mb-4">
            <div class="card-header py-3 justify-content-between d-flex">
                <h6 class="m-0 font-weight-bold text-primary">Incoming</h6>
                <a href="{% url 'transfer:create' %}" class="btn btn-primary">
                    New transfer
                </a>
            </div>
            <div class="card-body">
                <p>There are {{ object_list.count }} transfers right now!</p>
                <div class="list-group">
                    {% for transfer in object_list %}
                          <a href="{% url 'transfer:detail' pk=transfer.pk %}" class="list-group-item list-group-item-action">
                                 <div class="d-flex w-100 justify-content-between">
                                     <h5 class="mb-1">
                                         <strong>Sender: </strong>{{ transfer.sender }}
                                     </h5>
                                    <small class="text-muted">Status: {{ transfer.get_status_display }}</small>
                                 </div>
                                <p>
                                    <strong>Transfer: </strong>{{ transfer.get_method_display }}
                                </p>
                                 <p class="mb-1">
                                    <b>Title:</b> {{ transfer.title }} / <b>Date:</b> {{ transfer.created }} / <b>Amount:</b> {{ transfer.amount }}
                                 </p>
                                 <small class="text-muted">Reference: {{ transfer.reference }}</small>
                          </a>
                        <br />
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock content%}

backend/templates/transfer/outgoing_list.html
{% extends 'base_index.html' %}
{% load static %}

{% block title %}{{ block.super }} - Transfers List{% endblock title %}

{% block content %}

    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Transfers</h1>
        </div>
        <div class="card shadow mb-4">
            <div class="card-header py-3 justify-content-between d-flex">
                <h6 class="m-0 font-weight-bold text-primary">Outgoing</h6>
                <a href="{% url 'transfer:create' %}" class="btn btn-primary">
                    New transfer
                </a>
            </div>
            <div class="card-body">
                <p>There are {{ object_list.count }} transfers right now!</p>
                <div class="list-group">
                    {% for transfer in object_list %}
                          <a href="{% url 'transfer:detail' pk=transfer.pk %}" class="list-group-item list-group-item-action">
                                 <div class="d-flex w-100 justify-content-between">
                                     <h5 class="mb-1">
                                         <strong>Receiver: </strong>{{ transfer.receiver }}
                                     </h5>
                                    <small class="text-muted">Status: {{ transfer.get_status_display }}</small>
                                 </div>
                                <p>
                                    <strong>Transfer: </strong>{{ transfer.get_method_display }}
                                </p>
                                 <p class="mb-1">
                                    <b>Title:</b> {{ transfer.title }} / <b>Date:</b> {{ transfer.created }} / <b>Amount:</b> {{ transfer.amount }}
                                 </p>
                                 <small class="text-muted">Reference: {{ transfer.reference }}</small>
                          </a>
                        <br />
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock content%}