backend/account/urls.py
from django.urls import path

from account.views import *

app_name = 'account'

user_urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='create'),
    path('detail/<pk>/', UserDetailView.as_view(), name='detail'),
    path('password/change/', UserPasswordChangeView.as_view(), name='password-change'),
    path('password/reset/', UserPasswordResetView.as_view(), name='password-reset'),
    path('password/reset/done/', UserPasswordResetDoneView.as_view(), name='password-reset-done'),
    path('password/reset/confirm/<uidb64>/<token>/',
         UserPasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('password/reset/complete/', UserPasswordResetCompleteView.as_view(), name='password-reset-complete'),
]

bank_account_urlpatterns = [
    path('bank-account/list/', BankAccountListView.as_view(), name='bank-account-list'),
    path('bank-account/detail/<pk>/', BankAccountDetailView.as_view(), name='bank-account-detail'),
    path('bank-account/create/', BankAccountCreateView.as_view(), name='bank-account-create')

]
urlpatterns = user_urlpatterns + bank_account_urlpatterns

backend/backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import routers, permissions

from account.api.views import BankAccountViewSet
from account.views import HomePage
from card.api.views import CardViewSet
from transfer.api.views import TransferViewSet


schema_view = get_schema_view(
   openapi.Info(
      title="Bank API",
      default_version='v1',
      description="RESTful API for Bank.",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.IsAuthenticatedOrReadOnly,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', HomePage.as_view(), name='index'),
    path('account/', include('account.urls', namespace='account')),
    path('transfer/', include('transfer.urls', namespace='transfer')),
    path('card/', include('card.urls', namespace='card'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


router = routers.DefaultRouter()
router.register('bank-accounts', BankAccountViewSet, 'bank-account')
router.register('transfers', TransferViewSet, 'transfer')
router.register('cards', CardViewSet, 'card')

urlpatterns_api = [
    path('api/', include(router.urls)),
    path('api/swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

urlpatterns += urlpatterns_api

handler404 = 'account.views.custom_page_not_found'
handler500 = 'account.views.custom_server_error'
handler403 = 'account.views.custom_permission_denied'
handler400 = 'account.views.custom_bad_request'

backend/card/urls.py
from django.urls import path

from card.views import *

app_name = 'card'

urlpatterns = [
    path('list/', CardListView.as_view(), name='list'),
    path('detail/<pk>', CardDetailView.as_view(), name='detail'),
    path('create/', CardCreateView.as_view(), name='create')
]

backend/templates/modal/logout.html
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="{% url 'account:login' %}">Logout</a>
            </div>
        </div>
    </div>
</div>